[project]
name = "supply-chain-tracking"
authors = []
description = "A blockchain-powered supply chain tracking solution"
telemetry = false
requirements = []

[contracts.supply-chain]
path = "contracts/supply-chain.clar"
depends_on = []

[contracts.product-certification]
path = "contracts/product-certification.clar"
depends_on = ["supply-chain"]

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
